export enum LANGUAGES {
  ENGLISH = 'english',
  SPANISH = 'spanish',
  FRENCH = 'french',
  GERMAN = 'german',
  ITALIAN = 'italian',
  PORTUGUESE = 'portuguese',
  RUSSIAN = 'russian',
  CHINESE = 'chinese',
  JAPANESE = 'japanese',
  KOREAN = 'korean',
  ARABIC = 'arabic',
  HINDI = 'hindi',
  TURKISH = 'turkish',
  SWEDISH = 'swedish',
  DANISH = 'danish',
  NORWEGIAN = 'norwegian',
  FINNISH = 'finnish',
  DUTCH = 'dutch',
  GREEK = 'greek',
  THAI = 'thai',
  VIETNAMESE = 'vietnamese'
}